version: "3.9"

networks:
  my-network:
    driver: bridge

volumes:
  postgresql-data: 
services:
    db:
        container_name: 'postgres'
        image: "postgres"
        environment:
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "admin"
            POSTGRES_DB: "University"
        ports:
        - "5432:5432"
        networks:
        - my-network
        volumes:
        - postgresql-data:/var/lib/postgresql/data
    

    university:
        image: "university:1.0.1"
        container_name: 'university-service'
        ports:
        - "1234:80"     
        environment:
            ASPNETCORE_ENVIRONMENT: "Development"  
        networks:
        - my-network
        depends_on:
        - db
